name: Android CI Signed

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEYSTORE }}" | base64 --decode > mykey.jks

      - name: Build Signed APK
        run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=mykey.jks -Pandroid.injected.signing.store.password=${{ secrets.SIGNING_STORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.SIGNING_KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Build Signed AAB
        run: ./gradlew bundleRelease -Pandroid.injected.signing.store.file=mykey.jks -Pandroid.injected.signing.store.password=${{ secrets.SIGNING_STORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.SIGNING_KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: app/build/outputs/apk/release/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: signed-aab
          path: app/build/outputs/bundle/release/*.aab
